openapi: 3.0.0
info:
  title: Task Manager API
  version: 1.0.0
  description: API для управления задачами и комментариями к ним.
servers:
  - url: http://localhost:9090/api
paths:
  /tasks:
    get:
      summary: Получить все задачи
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: filters
          in: query
          required: false
          schema:
            type: object
      responses:
        '200':
          description: Успешный ответ с задачами
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
    post:
      summary: Создать новую задачу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Задача успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    put:
      summary: Обновить задачу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Задача успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{id}:
    get:
      summary: Получить задачу по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ с задачей
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    delete:
      summary: Удалить задачу по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Задача успешно удалена
  /tasks/{taskId}/{statusCode}:
    patch:
      summary: Обновить статус задачи
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
        - name: statusCode
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Статус задачи успешно обновлён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{taskId}/performer/{userId}:
    patch:
      summary: Обновить исполнителя задачи
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Исполнитель задачи успешно обновлён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/comment/{taskId}:
    post:
      summary: Добавить комментарий к задаче
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '201':
          description: Комментарий успешно добавлен
          content:
            application/json:
              schema:
                type: string
    get:
      summary: Получить комментарии к задаче
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Успешный ответ с комментариями
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/TaskComment'
  /tasks/author/{id}:
    get:
      summary: Получить задачи по автору
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: filters
          in: query
          required: false
          schema:
            type: object
      responses:
        '200':
          description: Успешный ответ с задачами
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
  /tasks/performer/{id}:
    get:
      summary: Получить задачи по исполнителю
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: filters
          in: query
          required: false
          schema:
            type: object
      responses:
        '200':
          description: Успешный ответ с задачами
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
        performerId:
          type: integer
        authorId:
          type: integer
        createdDate:
          type: string
          format: date-time
        updatedDate:
          type: string
          format: date-time
    TaskComment:
      type: object
      properties:
        id:
          type: integer
        taskId:
          type: integer
        comment:
          type: string
        createdDate:
          type: string
          format: date-time
